import {
  Backpack,
  BellElectric,
  Book,
  BookA,
  BookCopy,
  BookText,
  Clock,
  Computer,
  FerrisWheel,
  GraduationCap,
  Library,
  LibraryBig,
  NotebookText,
  NotepadText,
  School,
  SquareLibrary,
  University,
  Wallet,
} from 'lucide-react'

export const DataServices = [
  {
    title: 'CBT',
    icon: <Computer size={36} />,
    desc: 'Computer Based Test',
    link: '/cbt',
  },
  {
    title: 'SIMABAMA',
    icon: <Backpack size={36} />,
    desc: 'Sistem Manajemen Pendaftaran Mahasiswa Baru',
    link: '/',
  },
  {
    title: 'SIPEMKUL',
    icon: <NotepadText size={36} />,
    desc: 'Sistem Informasi Pendaftaran Mata Kuliah',
    link: '/',
  },
  {
    title: 'SIJADKUL',
    icon: <Clock size={36} />,
    desc: 'Sistem Informasi Jadwal Kuliah',
    link: '/',
  },
  {
    title: 'SITRANS',
    icon: <BookText size={36} />,
    desc: 'Sistem Informasi Transkrip',
    link: '/',
  },
  {
    title: 'SIBIKUL',
    icon: <Wallet size={36} />,
    desc: 'Sistem Infromasi Biaya Kuliah',
    link: '/',
  },
  {
    title: 'SIPENDOS',
    icon: <BellElectric size={36} />,
    desc: 'Sistem Pengisian dan Evaluasi Dosen',
    link: '/',
  },
  {
    title: 'SIPEPI',
    icon: <NotebookText size={36} />,
    desc: 'Sistem Informasi Pengumuman dan Informasi Penting',
    link: '/',
  },
  {
    title: 'PERDIGIT',
    icon: <Library size={36} />,
    desc: 'Perpustakaan Digital Terkini',
    link: '/',
  },
  {
    title: 'SIPU',
    icon: <BookCopy size={36} />,
    desc: 'Sistem Informasi Pendaftaran Ujian',
    link: '/',
  },
  {
    title: 'SINAKAD',
    icon: <School size={36} />,
    desc: 'Sistem Informasi Konseling Akademik',
    link: '/',
  },
  {
    title: 'PELIMA',
    icon: <BookA size={36} />,
    desc: 'Pembelajaran Ilmiah Online',
    link: '/',
  },
  {
    title: 'ALUPET',
    icon: <FerrisWheel size={36} />,
    desc: 'Alumni Performance Tracking',
    link: '/',
  },
  {
    title: 'SP3',
    icon: <SquareLibrary size={36} />,
    desc: 'Sistem Pengelolaan Pengajaran dan Penelitian',
    link: '/',
  },
  {
    title: 'SISKA',
    icon: <GraduationCap size={36} />,
    desc: 'SIstem Informasi Skripsi Mahasiswa',
    link: '/',
  },
  {
    title: 'SIMAKARMA',
    icon: <LibraryBig size={36} />,
    desc: 'Sistem Manajemen Karya Ilmiah',
    link: '/',
  },
  {
    title: 'SIMAJU',
    icon: <Book size={36} />,
    desc: 'Sistem Manajemen Jurnal Mahasiswa',
    link: '/',
  },
  {
    title: 'SIBEMAT',
    icon: <University size={36} />,
    desc: 'Sistem Beasiswa Mahasiswa Terpilih',
    link: '/',
  },
]
